// file.save — the reliable way for the agent to produce a downloadable TEXT file.
// The SERVER writes it to the correct per-thread artifact dir (host-side), so
// there's no dependence on the agent's working dir, path choices, os.makedirs, or
// container file permissions. The chat endpoint then renders a download chip.
// (Binary files like docx/pptx/xlsx/images are still generated by the agent with
// code into the same dir — those need real libraries.)

import { mkdirSync, writeFileSync } from "node:fs";
import { join, basename } from "node:path";
import type { Env } from "@/env.js";
import type { BrokerTool } from "@/mcp-broker/protocol.js";
import { BrokerError } from "@/mcp-broker/protocol.js";

export function buildFileTools(env: Env): BrokerTool[] {
  return [
    {
      name: "file.save",
      description:
        "Save a TEXT file (markdown .md, csv, txt, json, html) and offer it to the user as a download. Pass `filename` (e.g. report.md) and the full `content`. ALWAYS use this for text-based downloadable files — do not write text files with code. (For binary files — docx, pptx, xlsx, images — generate them with code instead.)",
      inputSchema: {
        type: "object",
        properties: {
          filename: { type: "string", description: "e.g. report.md (extension sets the type)" },
          content: { type: "string", description: "the full file contents" },
        },
        required: ["filename", "content"],
        additionalProperties: false,
      },
      meta: { source: "system", writes: true },
      handle: async (args, ctx) => {
        const root = env.HERMES_ARTIFACTS_DIR;
        if (!root) throw new BrokerError("UPSTREAM", "File storage is not configured.");
        const threadId = (ctx.sessionKey ?? "").split(":").pop();
        if (!threadId) throw new BrokerError("VALIDATION", "No session to attach the file to.");
        const filename = basename(String(args.filename ?? "").trim());
        if (!filename || filename.startsWith(".")) throw new BrokerError("VALIDATION", "`filename` is required.");
        const content = String(args.content ?? "");
        const dir = join(root, threadId);
        mkdirSync(dir, { recursive: true });
        writeFileSync(join(dir, filename), content, "utf8");
        return { saved: filename, download: `/api/files/${threadId}/${encodeURIComponent(filename)}` };
      },
    },
  ];
}
