#!/bin/bash
# Basics OS Local Dev Setup
# Usage: ./scripts/dev-setup.sh
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

step() { echo -e "\n${GREEN}▶ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }

step "Basics OS Local Dev Setup"

# ─── .env file ──────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  step "Generating .env file..."
  AUTH_SECRET=$(openssl rand -hex 32 2>/dev/null || node -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  cat > .env << ENVEOF
# Basics OS Local Dev — auto-generated by scripts/dev-setup.sh

DATABASE_URL=postgresql://basicos:basicos_dev@localhost:5432/basicos
REDIS_URL=redis://localhost:6379
BETTER_AUTH_SECRET=${AUTH_SECRET}
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:3001

# Optional — add your API key to enable AI features:
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...

BASICOS_COMPANY_NAME=Acme Corp
BASICOS_ACCENT_COLOR=#6366f1
ENVEOF
  echo ".env created with auto-generated auth secret"
else
  echo ".env already exists — skipping"
fi

# ─── Dependencies ────────────────────────────────────────────────────────────
step "Installing dependencies..."
pnpm install

# ─── Docker services ─────────────────────────────────────────────────────────
step "Starting PostgreSQL and Redis..."
docker-compose up -d
echo "Waiting for database to be ready..."
sleep 3

# Wait for postgres
for i in {1..15}; do
  if docker-compose exec -T postgres pg_isready -U basicos >/dev/null 2>&1; then
    break
  fi
  echo "  Waiting... ($i/15)"
  sleep 2
done

# ─── Build packages ──────────────────────────────────────────────────────────
step "Building packages..."
pnpm --filter @basicos/shared build
pnpm --filter @basicos/db build
pnpm --filter @basicos/auth build
pnpm --filter @basicos/ui build
pnpm --filter @basicos/api build

# ─── Database ────────────────────────────────────────────────────────────────
step "Running migrations..."
# Build happens above; drizzle.config.ts points to ./dist/schema/index.js,
# so tsc must run before drizzle-kit. The migrate script (tsc && drizzle-kit push)
# handles this automatically. Alternatively run push directly:
pnpm db:migrate 2>/dev/null || warn "Migration failed — database may already be initialized"

step "Seeding demo data..."
pnpm db:seed 2>/dev/null || warn "Seed failed — database may already have data"

# ─── Done ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   ✅  Basics OS ready for local development!  ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""
echo "  Start the servers:"
echo ""
echo "    Terminal 1:  pnpm --filter @basicos/api dev"
echo "    Terminal 2:  pnpm --filter @basicos/web dev"
echo ""
echo "  Then open:  http://localhost:3000"
echo ""
echo "  Login with:"
echo "    Email:    admin@acme.example.com"
echo "    Password: (any password — auth uses Better Auth)"
echo ""
echo "  To enable AI:  add ANTHROPIC_API_KEY to .env"
echo ""
