/**
 * Cross-platform local dev setup (Windows, Mac, Linux).
 * Usage: bun scripts/dev-setup.ts  (or bun run dev:setup from repo root)
 */
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { join } from "node:path";

const REPO_ROOT = join(import.meta.dir, "..");

const step = (msg: string): void => {
  console.log("\n\u001b[32m\u25b6 " + msg + "\u001b[0m");
};

const warn = (msg: string): void => {
  console.warn("\u001b[33m\u26a0 " + msg + "\u001b[0m");
};

const run = async (
  cmd: string,
  args: string[],
  opts?: { cwd?: string; ignoreFailure?: boolean },
): Promise<boolean> => {
  const cwd = opts?.cwd ?? REPO_ROOT;
  const proc = Bun.spawn([cmd, ...args], {
    cwd,
    stdout: "inherit",
    stderr: "inherit",
    stdin: "inherit",
  });
  const exit = await proc.exited;
  if (exit !== 0 && !opts?.ignoreFailure) {
    return false;
  }
  return true;
};

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

const main = async (): Promise<void> => {
  step("Basics OS Local Dev Setup");

  // ─── Bun check ─────────────────────────────────────────────────────────────
  try {
    const v = Bun.version;
    console.log("Using Bun " + v);
  } catch {
    console.error("Bun is required. Install from https://bun.sh");
    process.exit(1);
  }

  // ─── .env file ─────────────────────────────────────────────────────────────
  const envPath = join(REPO_ROOT, ".env");
  if (!existsSync(envPath)) {
    step("Generating .env file...");
    const authSecret = randomBytes(32).toString("hex");
    const envContent = `# Basics OS Local Dev — auto-generated by scripts/dev-setup.ts

DATABASE_URL=postgresql://basicos:basicos_dev@localhost:5432/basicos
REDIS_URL=redis://localhost:6379
BETTER_AUTH_SECRET=${authSecret}
BETTER_AUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:3001

# Optional — add your API key to enable AI features:
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...

BASICOS_COMPANY_NAME=Acme Corp
BASICOS_ACCENT_COLOR=#6366f1
`;
    await writeFile(envPath, envContent);
    console.log(".env created with auto-generated auth secret");
  } else {
    console.log(".env already exists — skipping");
  }

  // ─── Dependencies ─────────────────────────────────────────────────────────
  step("Installing dependencies...");
  const installOk = await run("bun", ["install"]);
  if (!installOk) {
    console.error("bun install failed");
    process.exit(1);
  }

  // ─── Build workspace packages ─────────────────────────────────────────────
  step("Building workspace packages...");
  const buildOk = await run("bun", ["run", "build", "--filter=./packages/*"], {
    ignoreFailure: true,
  });
  if (!buildOk) {
    warn("Build had errors — try: bun run build --filter=@basicsos/ui --filter=@basicsos/shared");
  }

  // ─── Docker services ───────────────────────────────────────────────────────
  step("Starting PostgreSQL and Redis...");
  const dockerComposeOk = await run("docker", ["compose", "up", "-d"], {
    ignoreFailure: true,
  });
  if (!dockerComposeOk) {
    const dockerComposeLegacyOk = await run("docker-compose", ["up", "-d"], {
      ignoreFailure: true,
    });
    if (!dockerComposeLegacyOk) {
      warn("Docker not available or failed — start Postgres and Redis manually.");
    }
  }
  console.log("Waiting for database to be ready...");
  await sleep(5000);

  // Wait for postgres (try docker exec pg_isready if docker was used)
  for (let i = 0; i < 10; i++) {
    const ready = await run(
      "docker",
      ["compose", "exec", "-T", "postgres", "pg_isready", "-U", "basicos"],
      { ignoreFailure: true },
    );
    if (ready) break;
    const readyLegacy = await run(
      "docker-compose",
      ["exec", "-T", "postgres", "pg_isready", "-U", "basicos"],
      { ignoreFailure: true },
    );
    if (readyLegacy) break;
    console.log("  Waiting... (" + (i + 1) + "/10)");
    await sleep(2000);
  }

  // ─── Database ──────────────────────────────────────────────────────────────
  step("Running migrations...");
  await run("bun", ["db:migrate"], { ignoreFailure: true });
  step("Seeding demo data...");
  await run("bun", ["db:seed"], { ignoreFailure: true });

  // ─── Done ─────────────────────────────────────────────────────────────────
  console.log("");
  console.log("\u001b[32m\u2554\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2551\u001b[0m");
  console.log("\u001b[32m\u2551   \u2713  Basics OS ready for local development!  \u2551\u001b[0m");
  console.log("\u001b[32m\u255a\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u2550\u255d\u001b[0m");
  console.log("");
  console.log("  Start the servers:");
  console.log("");
  console.log("    Terminal 1:  bun --filter @basicsos/api dev");
  console.log("    Terminal 2:  bun --filter @basicsos/web dev");
  console.log("");
  console.log("  Then open:  http://localhost:3000");
  console.log("");
  console.log("  Login with:");
  console.log("    Email:    admin@acme.example.com");
  console.log("    Password: password");
  console.log("");
  console.log("  To enable AI:  add ANTHROPIC_API_KEY to .env");
  console.log("");
};

main().catch((err) => {
  console.error("Setup failed:", err);
  process.exit(1);
});
