#!/bin/bash
# Basics OS Local Dev Setup
# Usage: ./scripts/dev-setup.sh
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

step() { echo -e "\n${GREEN}▶ $1${NC}"; }
warn() { echo -e "${YELLOW}⚠ $1${NC}"; }

step "Basics OS Local Dev Setup"

# ─── Bun check ───────────────────────────────────────────────────────────────
if ! command -v bun &>/dev/null; then
  echo "Bun is required but not installed."
  echo "Install it from https://bun.sh or run: curl -fsSL https://bun.sh/install | bash"
  exit 1
fi
echo "Using $(bun --version | head -1)"

# ─── .env file ──────────────────────────────────────────────────────────────
if [ ! -f .env ]; then
  step "Generating .env file..."
  AUTH_SECRET=$(openssl rand -hex 32 2>/dev/null || bun -e "console.log(require('crypto').randomBytes(32).toString('hex'))")
  cat > .env << ENVEOF
# Basics OS Local Dev — auto-generated by scripts/dev-setup.sh

DATABASE_URL=postgresql://basicos:basicos_dev@localhost:5432/basicos
REDIS_URL=redis://localhost:6379
BETTER_AUTH_SECRET=${AUTH_SECRET}
BETTER_AUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://localhost:3001

# Optional — add your API key to enable AI features:
# ANTHROPIC_API_KEY=sk-ant-...
# OPENAI_API_KEY=sk-...

BASICOS_COMPANY_NAME=Acme Corp
BASICOS_ACCENT_COLOR=#6366f1
ENVEOF
  echo ".env created with auto-generated auth secret"
else
  echo ".env already exists — skipping"
fi

# ─── Dependencies ────────────────────────────────────────────────────────────
step "Installing dependencies..."
bun install

# ─── Docker services ─────────────────────────────────────────────────────────
step "Starting PostgreSQL and Redis..."
docker-compose up -d
echo "Waiting for database to be ready..."
sleep 3

# Wait for postgres
for i in {1..15}; do
  if docker-compose exec -T postgres pg_isready -U basicos >/dev/null 2>&1; then
    break
  fi
  echo "  Waiting... ($i/15)"
  sleep 2
done

# ─── Database ────────────────────────────────────────────────────────────────
step "Running migrations..."
# drizzle.config.ts points to ./src/schema/index.ts — Bun runs it natively,
# no tsc pre-build required.
bun db:migrate 2>/dev/null || warn "Migration failed — database may already be initialized"

step "Seeding demo data..."
bun db:seed 2>/dev/null || warn "Seed failed — database may already have data"

# ─── Done ────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║   ✅  Basics OS ready for local development!  ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════╝${NC}"
echo ""
echo "  Start the servers:"
echo ""
echo "    Terminal 1:  bun --filter @basicsos/api dev"
echo "    Terminal 2:  bun --filter @basicsos/web dev"
echo ""
echo "  Then open:  http://localhost:3000"
echo ""
echo "  Login with:"
echo "    Email:    admin@acme.example.com"
echo "    Password: password"
echo ""
echo "  To enable AI:  add ANTHROPIC_API_KEY to .env"
echo ""
