import { createInterface } from "node:readline";
import { writeFile } from "node:fs/promises";
import { randomBytes } from "node:crypto";

const ask = (rl: ReturnType<typeof createInterface>, question: string): Promise<string> =>
  new Promise((resolve) => rl.question(question, resolve));

// Escape a value for safe .env file inclusion (escape quotes and backslashes)
const escapeEnvValue = (value: string): string =>
  value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n");

const validateEmail = (email: string): boolean => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
const validateUrl = (url: string): boolean => {
  try {
    new URL(url);
    return true;
  } catch {
    return false;
  }
};

const main = async (): Promise<void> => {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  console.warn("Welcome to Basics OS Setup Wizard\n");

  const companyName = await ask(rl, "Company name: ");
  if (!companyName.trim()) {
    rl.close();
    throw new Error("Company name is required");
  }

  const adminEmail = await ask(rl, "Admin email: ");
  if (!validateEmail(adminEmail)) {
    rl.close();
    throw new Error(`Invalid email: ${adminEmail}`);
  }

  const appUrl = await ask(rl, "App URL (e.g. https://os.acmecorp.com): ");
  if (!validateUrl(appUrl)) {
    rl.close();
    throw new Error(`Invalid URL: ${appUrl}`);
  }

  const dbUrl =
    (await ask(
      rl,
      "PostgreSQL URL (default: postgresql://basicos:CHANGE_ME@localhost:5432/basicos): ",
    )) || "postgresql://basicos:CHANGE_ME@localhost:5432/basicos";

  const redisUrl =
    (await ask(rl, "Redis URL (default: redis://localhost:6379): ")) || "redis://localhost:6379";

  console.warn("\nAI features — choose how to enable them:");
  console.warn("  1. Managed key from basicsos.com (covers all models, no accounts needed)");
  console.warn("  2. Your own Anthropic key (ANTHROPIC_API_KEY)");
  console.warn("  3. Your own OpenAI key (OPENAI_API_KEY)");
  console.warn("  Leave blank to configure later — everything works without AI keys.\n");

  const aiChoice = await ask(rl, "Enter 1, 2, 3, or leave blank: ");
  let apiKeyLine =
    "# Add an AI key to enable the assistant, summarization, and embeddings:\n# AI_API_KEY=bsk_live_...   (basicsos.com managed key)\n# ANTHROPIC_API_KEY=sk-ant-...\n# OPENAI_API_KEY=sk-...";

  if (aiChoice.trim() === "1") {
    const managedKey = await ask(rl, "Managed API key (from basicsos.com/keys): ");
    if (managedKey.trim()) {
      apiKeyLine = `AI_API_KEY="${escapeEnvValue(managedKey.trim())}"\nAI_API_URL=https://api.basicsos.com`;
    }
  } else if (aiChoice.trim() === "2") {
    const anthropicKey = await ask(rl, "Anthropic API key (sk-ant-...): ");
    if (anthropicKey.trim())
      apiKeyLine = `ANTHROPIC_API_KEY="${escapeEnvValue(anthropicKey.trim())}"`;
  } else if (aiChoice.trim() === "3") {
    const openaiKey = await ask(rl, "OpenAI API key (sk-...): ");
    if (openaiKey.trim()) apiKeyLine = `OPENAI_API_KEY="${escapeEnvValue(openaiKey.trim())}"`;
  }

  // Use cryptographically secure random bytes for the auth secret
  const authSecret = randomBytes(32).toString("hex");

  const envContent = [
    `# Basics OS Configuration — generated by setup wizard`,
    `# IMPORTANT: Review all values before starting. Set a strong POSTGRES_PASSWORD.`,
    `BASICOS_COMPANY_NAME="${escapeEnvValue(companyName.trim())}"`,
    `DATABASE_URL="${escapeEnvValue(dbUrl)}"`,
    `REDIS_URL="${escapeEnvValue(redisUrl)}"`,
    `BETTER_AUTH_SECRET="${authSecret}"`,
    `NEXT_PUBLIC_APP_URL="${escapeEnvValue(appUrl)}"`,
    `NEXT_PUBLIC_API_URL="${escapeEnvValue(appUrl.replace("https://", "https://api.").replace("http://", "http://api."))}"`,
    apiKeyLine,
    `BASICOS_ACCENT_COLOR="#6366f1"`,
    ``,
    `# First admin account`,
    `BASICOS_ADMIN_EMAIL="${escapeEnvValue(adminEmail)}"`,
    ``,
    `# Database credentials (used by docker-compose.prod.yml)`,
    `# IMPORTANT: Change POSTGRES_PASSWORD before starting in production`,
    `POSTGRES_PASSWORD=CHANGE_ME_IN_PRODUCTION`,
  ].join("\n");

  await writeFile(".env", envContent);
  console.warn(
    "\n.env file written. Run docker-compose -f docker-compose.prod.yml up -d to start.",
  );

  rl.close();
};

main().catch(console.error);
